services:
  db:
    image: postgres:16
    ports:
      - "5433:5432"
    env_file:
      - ./server/.env
    volumes:
      - docker_test_pgdata:/var/lib/postgresql/data

volumes:
  docker_test_pgdata:
