services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    working_dir: /app
    env_file:
      - ./client/.env.local

  server:
    build: ./server
    ports:
      - "8000:8000"
    volumes:
      - ./server:/app
      - /app/node_modules
    working_dir: /app
    env_file:
      - ./server/.env.local
    depends_on:
      - db

  db:
    image: postgres:16
    ports:
      - "5433:5432"
    env_file:
      - ./server/.env.local
    volumes:
      - docker_test_pgdata:/var/lib/postgresql/data

volumes:
  docker_test_pgdata:
